/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WriterOnboardingRouteImport } from './routes/writer-onboarding'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterClientRouteImport } from './routes/register/client'
import { Route as RegisterWriterRouteImport } from './routes/register/writer'
import { Route as WriterOnboardingApplyRouteImport } from './routes/writer-onboarding.apply'
import { Route as WriterOnboardingApprovedRouteImport } from './routes/writer-onboarding.approved'
import { Route as WriterOnboardingPendingRouteImport } from './routes/writer-onboarding.pending'
import { Route as WriterOnboardingRejectedRouteImport } from './routes/writer-onboarding.rejected'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterOnboardingRoute = WriterOnboardingRouteImport.update({
  id: '/writer-onboarding',
  path: '/writer-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterClientRoute = RegisterClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterWriterRoute = RegisterWriterRouteImport.update({
  id: '/writer',
  path: '/writer',
  getParentRoute: () => RegisterRoute,
} as any)
const WriterOnboardingApplyRoute = WriterOnboardingApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => WriterOnboardingRoute,
} as any)
const WriterOnboardingApprovedRoute =
  WriterOnboardingApprovedRouteImport.update({
    id: '/approved',
    path: '/approved',
    getParentRoute: () => WriterOnboardingRoute,
  } as any)
const WriterOnboardingPendingRoute = WriterOnboardingPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => WriterOnboardingRoute,
} as any)
const WriterOnboardingRejectedRoute =
  WriterOnboardingRejectedRouteImport.update({
    id: '/rejected',
    path: '/rejected',
    getParentRoute: () => WriterOnboardingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/writer-onboarding': typeof WriterOnboardingRouteWithChildren
  '/register/client': typeof RegisterClientRoute
  '/register/writer': typeof RegisterWriterRoute
  '/writer-onboarding/apply': typeof WriterOnboardingApplyRoute
  '/writer-onboarding/approved': typeof WriterOnboardingApprovedRoute
  '/writer-onboarding/pending': typeof WriterOnboardingPendingRoute
  '/writer-onboarding/rejected': typeof WriterOnboardingRejectedRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/writer-onboarding': typeof WriterOnboardingRouteWithChildren
  '/register/client': typeof RegisterClientRoute
  '/register/writer': typeof RegisterWriterRoute
  '/writer-onboarding/apply': typeof WriterOnboardingApplyRoute
  '/writer-onboarding/approved': typeof WriterOnboardingApprovedRoute
  '/writer-onboarding/pending': typeof WriterOnboardingPendingRoute
  '/writer-onboarding/rejected': typeof WriterOnboardingRejectedRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/writer-onboarding': typeof WriterOnboardingRouteWithChildren
  '/register/client': typeof RegisterClientRoute
  '/register/writer': typeof RegisterWriterRoute
  '/writer-onboarding/apply': typeof WriterOnboardingApplyRoute
  '/writer-onboarding/approved': typeof WriterOnboardingApprovedRoute
  '/writer-onboarding/pending': typeof WriterOnboardingPendingRoute
  '/writer-onboarding/rejected': typeof WriterOnboardingRejectedRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/writer-onboarding'
    | '/register/client'
    | '/register/writer'
    | '/writer-onboarding/apply'
    | '/writer-onboarding/approved'
    | '/writer-onboarding/pending'
    | '/writer-onboarding/rejected'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/writer-onboarding'
    | '/register/client'
    | '/register/writer'
    | '/writer-onboarding/apply'
    | '/writer-onboarding/approved'
    | '/writer-onboarding/pending'
    | '/writer-onboarding/rejected'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/writer-onboarding'
    | '/register/client'
    | '/register/writer'
    | '/writer-onboarding/apply'
    | '/writer-onboarding/approved'
    | '/writer-onboarding/pending'
    | '/writer-onboarding/rejected'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  WriterOnboardingRoute: typeof WriterOnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer-onboarding': {
      id: '/writer-onboarding'
      path: '/writer-onboarding'
      fullPath: '/writer-onboarding'
      preLoaderRoute: typeof WriterOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/client': {
      id: '/register/client'
      path: '/client'
      fullPath: '/register/client'
      preLoaderRoute: typeof RegisterClientRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/writer': {
      id: '/register/writer'
      path: '/writer'
      fullPath: '/register/writer'
      preLoaderRoute: typeof RegisterWriterRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/writer-onboarding/apply': {
      id: '/writer-onboarding/apply'
      path: '/apply'
      fullPath: '/writer-onboarding/apply'
      preLoaderRoute: typeof WriterOnboardingApplyRouteImport
      parentRoute: typeof WriterOnboardingRoute
    }
    '/writer-onboarding/approved': {
      id: '/writer-onboarding/approved'
      path: '/approved'
      fullPath: '/writer-onboarding/approved'
      preLoaderRoute: typeof WriterOnboardingApprovedRouteImport
      parentRoute: typeof WriterOnboardingRoute
    }
    '/writer-onboarding/pending': {
      id: '/writer-onboarding/pending'
      path: '/pending'
      fullPath: '/writer-onboarding/pending'
      preLoaderRoute: typeof WriterOnboardingPendingRouteImport
      parentRoute: typeof WriterOnboardingRoute
    }
    '/writer-onboarding/rejected': {
      id: '/writer-onboarding/rejected'
      path: '/rejected'
      fullPath: '/writer-onboarding/rejected'
      preLoaderRoute: typeof WriterOnboardingRejectedRouteImport
      parentRoute: typeof WriterOnboardingRoute
    }
  }
}

interface RegisterRouteChildren {
  RegisterClientRoute: typeof RegisterClientRoute
  RegisterWriterRoute: typeof RegisterWriterRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterClientRoute: RegisterClientRoute,
  RegisterWriterRoute: RegisterWriterRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface WriterOnboardingRouteChildren {
  WriterOnboardingApplyRoute: typeof WriterOnboardingApplyRoute
  WriterOnboardingApprovedRoute: typeof WriterOnboardingApprovedRoute
  WriterOnboardingPendingRoute: typeof WriterOnboardingPendingRoute
  WriterOnboardingRejectedRoute: typeof WriterOnboardingRejectedRoute
}

const WriterOnboardingRouteChildren: WriterOnboardingRouteChildren = {
  WriterOnboardingApplyRoute: WriterOnboardingApplyRoute,
  WriterOnboardingApprovedRoute: WriterOnboardingApprovedRoute,
  WriterOnboardingPendingRoute: WriterOnboardingPendingRoute,
  WriterOnboardingRejectedRoute: WriterOnboardingRejectedRoute,
}

const WriterOnboardingRouteWithChildren =
  WriterOnboardingRoute._addFileChildren(WriterOnboardingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRouteWithChildren,
  WriterOnboardingRoute: WriterOnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
